site_name: Samarium Documentation 
copyright: Copyright &copy; 2021–2024 trag1c
repo_url: https://github.com/samarium-lang/Samarium
repo_name: samarium-lang/Samarium
nav:
  - Home: index.md
  - Examples: examples.md
  - Language Guide:
    - Numbers: numbers.md
    - Variables: variables.md
    - Operators: operators.md
    - Strings: strings.md
    - Comments: comments.md
    - Arrays: arrays.md
    - Tables: tables.md
    - Built-in Functions: builtins.md
    - Control Flow: controlflow.md
    - Null: null.md
    - Slices: slices.md
    - Zipping: zip.md
    - Enums: enums.md
    - Functions: functions.md
    - Modules: modules.md
    - Classes: classes.md
    - File I/O: fileio.md
    - Python Interop: interop.md
  - Standard Library:
    - collections module: stdcollections.md
    - datetime module: stddatetime.md
    - io module: stdio.md
    - iter module: stditer.md
    - math module: stdmath.md
    - operator module: stdoperator.md
    - random module: stdrandom.md
    - string module: stdstring.md
    - types module: stdtypes.md
  - Tools: tools.md
theme:
  name: material
  logo: assets/icon-white.png
  favicon: assets/icon-black.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra_javascript:
  - https://unpkg.com/shiki@0.10.1/dist/index.unpkg.iife.js
  - assets/script.js
extra_css:
  - assets/style.css
markdown_extensions:
  - admonition
  - pymdownx.superfences:
        custom_fences:
            - name: sm
              class: sm
  - footnotes
