name: Workflow for Codecov
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests and collect coverage
        run: |
          poetry run pytest --cov=.
          poetry run coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
